// generated by ucdgen.go; DO NOT EDIT

package main

type Char struct {
	Char   rune
	Romaji string
	Type   string
}

var hiraganaChars = []Char{
	{
		Char:   12354,
		Romaji: "A",
		Type:   "hiragana",
	},
	{
		Char:   12356,
		Romaji: "I",
		Type:   "hiragana",
	},
	{
		Char:   12358,
		Romaji: "U",
		Type:   "hiragana",
	},
	{
		Char:   12360,
		Romaji: "E",
		Type:   "hiragana",
	},
	{
		Char:   12362,
		Romaji: "O",
		Type:   "hiragana",
	},
	{
		Char:   12363,
		Romaji: "KA",
		Type:   "hiragana",
	},
	{
		Char:   12364,
		Romaji: "GA",
		Type:   "hiragana",
	},
	{
		Char:   12365,
		Romaji: "KI",
		Type:   "hiragana",
	},
	{
		Char:   12366,
		Romaji: "GI",
		Type:   "hiragana",
	},
	{
		Char:   12367,
		Romaji: "KU",
		Type:   "hiragana",
	},
	{
		Char:   12368,
		Romaji: "GU",
		Type:   "hiragana",
	},
	{
		Char:   12369,
		Romaji: "KE",
		Type:   "hiragana",
	},
	{
		Char:   12370,
		Romaji: "GE",
		Type:   "hiragana",
	},
	{
		Char:   12371,
		Romaji: "KO",
		Type:   "hiragana",
	},
	{
		Char:   12372,
		Romaji: "GO",
		Type:   "hiragana",
	},
	{
		Char:   12373,
		Romaji: "SA",
		Type:   "hiragana",
	},
	{
		Char:   12374,
		Romaji: "ZA",
		Type:   "hiragana",
	},
	{
		Char:   12375,
		Romaji: "SI",
		Type:   "hiragana",
	},
	{
		Char:   12376,
		Romaji: "ZI",
		Type:   "hiragana",
	},
	{
		Char:   12377,
		Romaji: "SU",
		Type:   "hiragana",
	},
	{
		Char:   12378,
		Romaji: "ZU",
		Type:   "hiragana",
	},
	{
		Char:   12379,
		Romaji: "SE",
		Type:   "hiragana",
	},
	{
		Char:   12380,
		Romaji: "ZE",
		Type:   "hiragana",
	},
	{
		Char:   12381,
		Romaji: "SO",
		Type:   "hiragana",
	},
	{
		Char:   12382,
		Romaji: "ZO",
		Type:   "hiragana",
	},
	{
		Char:   12383,
		Romaji: "TA",
		Type:   "hiragana",
	},
	{
		Char:   12384,
		Romaji: "DA",
		Type:   "hiragana",
	},
	{
		Char:   12385,
		Romaji: "TI",
		Type:   "hiragana",
	},
	{
		Char:   12386,
		Romaji: "DI",
		Type:   "hiragana",
	},
	{
		Char:   12388,
		Romaji: "TU",
		Type:   "hiragana",
	},
	{
		Char:   12389,
		Romaji: "DU",
		Type:   "hiragana",
	},
	{
		Char:   12390,
		Romaji: "TE",
		Type:   "hiragana",
	},
	{
		Char:   12391,
		Romaji: "DE",
		Type:   "hiragana",
	},
	{
		Char:   12392,
		Romaji: "TO",
		Type:   "hiragana",
	},
	{
		Char:   12393,
		Romaji: "DO",
		Type:   "hiragana",
	},
	{
		Char:   12394,
		Romaji: "NA",
		Type:   "hiragana",
	},
	{
		Char:   12395,
		Romaji: "NI",
		Type:   "hiragana",
	},
	{
		Char:   12396,
		Romaji: "NU",
		Type:   "hiragana",
	},
	{
		Char:   12397,
		Romaji: "NE",
		Type:   "hiragana",
	},
	{
		Char:   12398,
		Romaji: "NO",
		Type:   "hiragana",
	},
	{
		Char:   12399,
		Romaji: "HA",
		Type:   "hiragana",
	},
	{
		Char:   12400,
		Romaji: "BA",
		Type:   "hiragana",
	},
	{
		Char:   12401,
		Romaji: "PA",
		Type:   "hiragana",
	},
	{
		Char:   12402,
		Romaji: "HI",
		Type:   "hiragana",
	},
	{
		Char:   12403,
		Romaji: "BI",
		Type:   "hiragana",
	},
	{
		Char:   12404,
		Romaji: "PI",
		Type:   "hiragana",
	},
	{
		Char:   12405,
		Romaji: "HU",
		Type:   "hiragana",
	},
	{
		Char:   12406,
		Romaji: "BU",
		Type:   "hiragana",
	},
	{
		Char:   12407,
		Romaji: "PU",
		Type:   "hiragana",
	},
	{
		Char:   12408,
		Romaji: "HE",
		Type:   "hiragana",
	},
	{
		Char:   12409,
		Romaji: "BE",
		Type:   "hiragana",
	},
	{
		Char:   12410,
		Romaji: "PE",
		Type:   "hiragana",
	},
	{
		Char:   12411,
		Romaji: "HO",
		Type:   "hiragana",
	},
	{
		Char:   12412,
		Romaji: "BO",
		Type:   "hiragana",
	},
	{
		Char:   12413,
		Romaji: "PO",
		Type:   "hiragana",
	},
	{
		Char:   12414,
		Romaji: "MA",
		Type:   "hiragana",
	},
	{
		Char:   12415,
		Romaji: "MI",
		Type:   "hiragana",
	},
	{
		Char:   12416,
		Romaji: "MU",
		Type:   "hiragana",
	},
	{
		Char:   12417,
		Romaji: "ME",
		Type:   "hiragana",
	},
	{
		Char:   12418,
		Romaji: "MO",
		Type:   "hiragana",
	},
	{
		Char:   12420,
		Romaji: "YA",
		Type:   "hiragana",
	},
	{
		Char:   12422,
		Romaji: "YU",
		Type:   "hiragana",
	},
	{
		Char:   12424,
		Romaji: "YO",
		Type:   "hiragana",
	},
	{
		Char:   12425,
		Romaji: "RA",
		Type:   "hiragana",
	},
	{
		Char:   12426,
		Romaji: "RI",
		Type:   "hiragana",
	},
	{
		Char:   12427,
		Romaji: "RU",
		Type:   "hiragana",
	},
	{
		Char:   12428,
		Romaji: "RE",
		Type:   "hiragana",
	},
	{
		Char:   12429,
		Romaji: "RO",
		Type:   "hiragana",
	},
	{
		Char:   12431,
		Romaji: "WA",
		Type:   "hiragana",
	},
	{
		Char:   12432,
		Romaji: "WI",
		Type:   "hiragana",
	},
	{
		Char:   12433,
		Romaji: "WE",
		Type:   "hiragana",
	},
	{
		Char:   12434,
		Romaji: "WO",
		Type:   "hiragana",
	},
	{
		Char:   12435,
		Romaji: "N",
		Type:   "hiragana",
	},
	{
		Char:   12436,
		Romaji: "VU",
		Type:   "hiragana",
	},
}

var katakanaChars = []Char{
	{
		Char:   12450,
		Romaji: "A",
		Type:   "katakana",
	},
	{
		Char:   12452,
		Romaji: "I",
		Type:   "katakana",
	},
	{
		Char:   12454,
		Romaji: "U",
		Type:   "katakana",
	},
	{
		Char:   12456,
		Romaji: "E",
		Type:   "katakana",
	},
	{
		Char:   12458,
		Romaji: "O",
		Type:   "katakana",
	},
	{
		Char:   12459,
		Romaji: "KA",
		Type:   "katakana",
	},
	{
		Char:   12460,
		Romaji: "GA",
		Type:   "katakana",
	},
	{
		Char:   12461,
		Romaji: "KI",
		Type:   "katakana",
	},
	{
		Char:   12462,
		Romaji: "GI",
		Type:   "katakana",
	},
	{
		Char:   12463,
		Romaji: "KU",
		Type:   "katakana",
	},
	{
		Char:   12464,
		Romaji: "GU",
		Type:   "katakana",
	},
	{
		Char:   12465,
		Romaji: "KE",
		Type:   "katakana",
	},
	{
		Char:   12466,
		Romaji: "GE",
		Type:   "katakana",
	},
	{
		Char:   12467,
		Romaji: "KO",
		Type:   "katakana",
	},
	{
		Char:   12468,
		Romaji: "GO",
		Type:   "katakana",
	},
	{
		Char:   12469,
		Romaji: "SA",
		Type:   "katakana",
	},
	{
		Char:   12470,
		Romaji: "ZA",
		Type:   "katakana",
	},
	{
		Char:   12471,
		Romaji: "SI",
		Type:   "katakana",
	},
	{
		Char:   12472,
		Romaji: "ZI",
		Type:   "katakana",
	},
	{
		Char:   12473,
		Romaji: "SU",
		Type:   "katakana",
	},
	{
		Char:   12474,
		Romaji: "ZU",
		Type:   "katakana",
	},
	{
		Char:   12475,
		Romaji: "SE",
		Type:   "katakana",
	},
	{
		Char:   12476,
		Romaji: "ZE",
		Type:   "katakana",
	},
	{
		Char:   12477,
		Romaji: "SO",
		Type:   "katakana",
	},
	{
		Char:   12478,
		Romaji: "ZO",
		Type:   "katakana",
	},
	{
		Char:   12479,
		Romaji: "TA",
		Type:   "katakana",
	},
	{
		Char:   12480,
		Romaji: "DA",
		Type:   "katakana",
	},
	{
		Char:   12481,
		Romaji: "TI",
		Type:   "katakana",
	},
	{
		Char:   12482,
		Romaji: "DI",
		Type:   "katakana",
	},
	{
		Char:   12484,
		Romaji: "TU",
		Type:   "katakana",
	},
	{
		Char:   12485,
		Romaji: "DU",
		Type:   "katakana",
	},
	{
		Char:   12486,
		Romaji: "TE",
		Type:   "katakana",
	},
	{
		Char:   12487,
		Romaji: "DE",
		Type:   "katakana",
	},
	{
		Char:   12488,
		Romaji: "TO",
		Type:   "katakana",
	},
	{
		Char:   12489,
		Romaji: "DO",
		Type:   "katakana",
	},
	{
		Char:   12490,
		Romaji: "NA",
		Type:   "katakana",
	},
	{
		Char:   12491,
		Romaji: "NI",
		Type:   "katakana",
	},
	{
		Char:   12492,
		Romaji: "NU",
		Type:   "katakana",
	},
	{
		Char:   12493,
		Romaji: "NE",
		Type:   "katakana",
	},
	{
		Char:   12494,
		Romaji: "NO",
		Type:   "katakana",
	},
	{
		Char:   12495,
		Romaji: "HA",
		Type:   "katakana",
	},
	{
		Char:   12496,
		Romaji: "BA",
		Type:   "katakana",
	},
	{
		Char:   12497,
		Romaji: "PA",
		Type:   "katakana",
	},
	{
		Char:   12498,
		Romaji: "HI",
		Type:   "katakana",
	},
	{
		Char:   12499,
		Romaji: "BI",
		Type:   "katakana",
	},
	{
		Char:   12500,
		Romaji: "PI",
		Type:   "katakana",
	},
	{
		Char:   12501,
		Romaji: "HU",
		Type:   "katakana",
	},
	{
		Char:   12502,
		Romaji: "BU",
		Type:   "katakana",
	},
	{
		Char:   12503,
		Romaji: "PU",
		Type:   "katakana",
	},
	{
		Char:   12504,
		Romaji: "HE",
		Type:   "katakana",
	},
	{
		Char:   12505,
		Romaji: "BE",
		Type:   "katakana",
	},
	{
		Char:   12506,
		Romaji: "PE",
		Type:   "katakana",
	},
	{
		Char:   12507,
		Romaji: "HO",
		Type:   "katakana",
	},
	{
		Char:   12508,
		Romaji: "BO",
		Type:   "katakana",
	},
	{
		Char:   12509,
		Romaji: "PO",
		Type:   "katakana",
	},
	{
		Char:   12510,
		Romaji: "MA",
		Type:   "katakana",
	},
	{
		Char:   12511,
		Romaji: "MI",
		Type:   "katakana",
	},
	{
		Char:   12512,
		Romaji: "MU",
		Type:   "katakana",
	},
	{
		Char:   12513,
		Romaji: "ME",
		Type:   "katakana",
	},
	{
		Char:   12514,
		Romaji: "MO",
		Type:   "katakana",
	},
	{
		Char:   12516,
		Romaji: "YA",
		Type:   "katakana",
	},
	{
		Char:   12518,
		Romaji: "YU",
		Type:   "katakana",
	},
	{
		Char:   12520,
		Romaji: "YO",
		Type:   "katakana",
	},
	{
		Char:   12521,
		Romaji: "RA",
		Type:   "katakana",
	},
	{
		Char:   12522,
		Romaji: "RI",
		Type:   "katakana",
	},
	{
		Char:   12523,
		Romaji: "RU",
		Type:   "katakana",
	},
	{
		Char:   12524,
		Romaji: "RE",
		Type:   "katakana",
	},
	{
		Char:   12525,
		Romaji: "RO",
		Type:   "katakana",
	},
	{
		Char:   12527,
		Romaji: "WA",
		Type:   "katakana",
	},
	{
		Char:   12528,
		Romaji: "WI",
		Type:   "katakana",
	},
	{
		Char:   12529,
		Romaji: "WE",
		Type:   "katakana",
	},
	{
		Char:   12530,
		Romaji: "WO",
		Type:   "katakana",
	},
	{
		Char:   12531,
		Romaji: "N",
		Type:   "katakana",
	},
	{
		Char:   12532,
		Romaji: "VU",
		Type:   "katakana",
	},
	{
		Char:   12535,
		Romaji: "VA",
		Type:   "katakana",
	},
	{
		Char:   12536,
		Romaji: "VI",
		Type:   "katakana",
	},
	{
		Char:   12537,
		Romaji: "VE",
		Type:   "katakana",
	},
	{
		Char:   12538,
		Romaji: "VO",
		Type:   "katakana",
	},
}
